server:
  port: 8888

spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:///C:\Users\RIBEAUD\Desktop\USACH cursos\Tecnicas de ingeniera de software\PrestaBancoParte2\Backend-Microservices\config-data
  application:
    name: config-service