apiVersion: v1
kind: PersistentVolume
metadata:
  name: clientes-db-pv
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 512Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/clientes-db-data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clientes-db-pvc
  labels:
    app: mysql
    tier: database
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clientes-db
  labels:
    app: clientes-db-deployment
    tier: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clientes-db-pod
  template:
    metadata:
      labels:
        app: clientes-db-pod
        tier: database
    spec:
      containers:
        - name: mysql
          image: mysql:latest
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: DB_USER_CLIENTES
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: DB_PASSWORD_CLIENTES
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: DB_ROOT_PASSWORD
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: clientes-db-data
      volumes:
        - name: clientes-db-data
          persistentVolumeClaim:
            claimName: clientes-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: clientes-db-service
  labels:
    app: clientes-db-service
    tier: database
spec:
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
  selector:
    app: clientes-db-pod
    tier: database
  type: LoadBalancer