apiVersion: v1
kind: PersistentVolume
metadata:
  name: creditos-db-pv
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/creditos-db-data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: creditos-db-pvc
  labels:
    app: mysql
    tier: database
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: creditos-db-deployment
  labels:
    app: creditos-db-deployment
    tier: database
spec:
  selector:
    matchLabels:
      app: creditos-db-deployment
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: creditos-db-deployment
        tier: database
    spec:
      containers:
        - name: creditos-db
          image: mysql
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: DB_USER_CREDITOS
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: DB_PASSWORD_CREDITOS
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: DB_ROOT_PASSWORD
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: creditos-db-data
          lifecycle:
            postStart:
              exec:
                command:
                  - "/bin/sh"
                  - "-c"
                  - |
                    until mysqladmin ping -h localhost --silent; do
                      echo "Waiting for database to be ready...";
                      sleep 2;
                    done;
                    echo "Checking if database `creditos-db` exists...";
                    if ! mysql -u$MYSQL_USER -p$MYSQL_PASSWORD -e "USE `creditos-db`;" 2>/dev/null; then
                      echo "Database `creditos-db` does not exist. Creating...";
                      mysql -u$MYSQL_USER -p$MYSQL_PASSWORD -e "CREATE DATABASE `creditos-db`;";
                    else
                      echo "Database `creditos-db` already exists.";    
        volumes:
          - name: creditos-db-data
            persistentVolumeClaim:
              claimName: creditos-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: creditos-db-service
  labels:
    app: creditos-db-service
    tier: database
spec:
  ports:
    - port: 3307
      targetPort: 3306
      protocol: TCP
  selector:
    app: creditos-db-deployment
    tier: database
  type: LoadBalancer