apiVersion: apps/v1
kind: Deployment
metadata:
  name: simulacion-service
  labels:
    app: simulacion-service-deployment
spec:
  selector:
    matchLabels:
      app: simulacion-service-pod
  replicas: 1
  template:
    metadata:
      labels:
        app: simulacion-service-pod
    spec:
      containers:
        - name: simulacion-service
          image: rbdantoine/usuario-service-image
          env:
            - name: SERVER_PORT
              value: "0"
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: mysql-config-map
                  key: DB_HOST_SIMULACION
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: mysql-config-map
                  key: DB_PORT
            - name: DB_DBNAME
              valueFrom:
                configMapKeyRef:
                  name: mysql-config-map
                  key: DB_NAME_SIMULACION
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: DB_USER_SIMULACION
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: DB_PASSWORD_SIMULACION
            - name: CONFIG_SERVER_HOST
              value: "config-server"
            - name: EUREKA_HOST
              value: "eureka-server"
            - name: EUREKA_PORT
              value: "8761"
            - name: INSTANCE_HOSTNAME
              value: simulacion-service
---
apiVersion: v1
kind: Service
metadata:
  name: simulacion-service
  labels:
    app: simulacion-service-deployment
spec:
  clusterIP: None
  selector:
    app: simulacion-service-pod
  ports:
    - protocol: TCP
      port: 8080 
      targetPort: 8080